apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - image: wardviaene/k8-demo
    imagePullPolicy: IfNotPresent
    name: k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
