apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld
spec:
  ports:
  - port: 80
    targetport: nodejs-port
      protocol: TCP
  selector:
    app: helloworld
  type: LoadBalancer
