apiVersion: v1
kind: pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: hello-world
spec:
  containers:
  - image: lmtbelmonte/docker-training
    name: ks8-helloworld
    ports:
    - containerPort: 3000

